server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: qh_test
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.116.129:3306/seata_order?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true
    username: root
    password: root

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml

#seata配置
seata:
  enabled: true
  # 你的服务名称
  application-id: seata-server
  #这里的名字与seata服务端的file.conf中vgroup_mapping.my_test_tx_group = "seata-server"相同
  tx-service-group: qh_test
  # 开启数据源自动代理
  enable-auto-data-source-proxy: true

  use-jdk-proxy: false
  service:
    vgroup-mapping:
      default: seata-server
    enable-degrade: false
    disable-global-transaction: false

  config:
    type: nacos
    nacos:
      #application: seata-server
      serverAddr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: ""
      cluster: default
      username: ""
      password: ""
  registy:
    type: nacos
    nacos:
      application: seata-server
      serve-addr: 127.0.0.1:8848
      namespace: ""
      username: ""
      password: ""




# seata的配置
#seata:
#  enabled: true
#  application-id: seata-server
#  tx-service-group: default  # 此时不能变化，否则会出现io.seata.common.exception.FrameworkException: No available service
#  enable-auto-data-source-proxy: true
#  use-jdk-proxy: false
#  service:
#    vgroup-mapping:
#      default: seata-server
#    enable-degrade: false
#    disable-global-transaction: false
#  registry:
#    type: eureka
#    eureka:
#      weight: 1
#      service-url: http://localhost:7001/eureka/


  #  可以指定动态代理
  #  use-jdk-proxy: false
#  service:
#    vgroup-mapping:
#      #这里对应端的file.conf中vgroup-mapping.my_test_tx_group = "seata-server"
#      my_test_tx_group: SEATA
#    grouplist:
#      default: 127.0.0.1:8091
  # Eureka配置
#  registry:
#    type: eureka
#    eureka:
#      application: default
#      serviceUrl: http://localhost:8848/eureka/
#      weight: 1
