server:
  port: 80

eureka:
  client:
    register-with-eureka: true  #表示是否将自己注册进RurekaServer默认为true
    fetchRegistry: true  #是否从RurekaServer抓取已有的注册信息，默认为true,单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群


#设置feign客户端超时时间(openFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #建立连接后从服务器读取到可用资源所用时间
  ConnectTimeout: 6000
feign:
  hystrix:
    enabled: true  #true 在feign中开启hystrix,如果处理自身的容错就开启。开启方式与生产端不一样